### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by wangyuhao11111** [YuxuanSnow/Human3Diffusion#2]
OSError: ashawkey/imagedream-ipmv-diffusers does not appear to have a file named scheduler_config.json.
Hello, thank you for your great contribution. I encountered the issue mentioned above while reproducing it. How can I resolve this?

**Comment by YuxuanSnow** [comment]
Hi, thanks for your question. It looks like a diffuser version issue. Which diffuser version do you use?

**Comment by wangyuhao11111** [comment]
I find out that my diffuser version is 0.30.3.

**Comment by YuxuanSnow** [comment]
We use the same `diffusers` version. Can you then try `pip install transformers==4.45.1`?

**Comment by wangyuhao11111** [comment]
Thank you very much for your response! In addition to needing this step, I also downloaded the imagedream-ipmv-diffusers file to my local machine, and I successfully reproduced it with great results. It's truly a remarkable creation!

**Comment by YuxuanSnow** [comment]
Glad it works! Thank you for posting your solution to help other people, also appreciate for the nice words!
