### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by bro-chj** [YuxuanSnow/Human3Diffusion#3]
Thank you for your excellent work. But I found that your file named README.md may have some mistakes. You writed the command: git clone https://github.com/YuxuanSnow/gaussian-opacity-fields.git  which is the other paper's code instead of Human3D.

**Comment by YuxuanSnow** [comment]
Thank you for your interest! That's correct, we use the Gaussian Opacity Fields (GOF) by Yu et al. to perform the 3D-GS rendering, which is generated by Human-3Diffusion. I forked the GOF when I developed Human-3Diffusion since it is a little bit tailored to my needs.
